#!/bin/bash

##
## Stockr pre-commit hook
##
## Name this file as .git/hooks/pre-commit
## and set it to executable.
##
## @author BrendonCrawford
##

CHECK_TYPES=(
    "A"
    "M"
)

CHECK_EXTENSIONS=(
    "py"
)

REPO_DIR=$(cd "${GIT_DIR}/../"; pwd)
#REPO_DIR="../.."

cd "${REPO_DIR}/"
changed_files=$(git status --porcelain)

#echo "Changed Files: #${changed_files}#"

## Loop through changed rows
IFS_OLD="${IFS}"
IFS=""
while read -r changed_row; do
    #echo "Changed: #${changed_row}#"
    ## Staged files
    fstatus_staged="${changed_row:0:1}"
    ## Unstaged files
    fstatus_unstaged="${changed_row:1:1}"
    ## Filepath
    fpath="${changed_row:3}"
    ## Filename
    fname=$(basename "${fpath}")
    ## File extensions
    fext="${fname##*.}"
    #echo "Filepath: #${fpath}#"
    #echo "Filename: #${fname}#"
    #echo "Fileext: #${fext}#"
    ## If does not match a correct extension
    ## then continue
    if ! [[ "${CHECK_EXTENSIONS[@]}" =~ "${fext}" ]]; then
        #echo "Skipping (Extension): #${fpath}#, #${fext}#"
        continue;
    fi;
    ## If status type is one of the ones that
    ## we want to check
    if [[ "${CHECK_TYPES[@]}" =~ "${fstatus_staged}" ]]; then
        #echo "Checking: ${fpath}"
        bash ./external/python-validate/validate-file.bash "${fpath}"
        ## Exit with failure if no pass
        if [ ${?} -ne 0 ]; then
            #echo "Failed: ${fpath}"
            exit 1
        else
            :
            #echo "Passed: ${fpath}"
        fi
    else
        :
        #echo "Skipping (Unstaged): #${fpath}#"
    fi
done <<< "${changed_files}"
IFS="${IFS_OLD}"

exit 0

